# coding: utf-8

"""
    NSX API

    VMware NSX REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.aggregate_request import AggregateRequest  # noqa: F401,E501
from swagger_client.models.related_data_request import RelatedDataRequest  # noqa: F401,E501


class AggregateDataRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'primary': 'AggregateRequest',
        'related': 'list[RelatedDataRequest]'
    }

    attribute_map = {
        'primary': 'primary',
        'related': 'related'
    }

    def __init__(self, primary=None, related=None):  # noqa: E501
        """AggregateDataRequest - a model defined in Swagger"""  # noqa: E501

        self._primary = None
        self._related = None
        self.discriminator = None

        self.primary = primary
        if related is not None:
            self.related = related

    @property
    def primary(self):
        """Gets the primary of this AggregateDataRequest.  # noqa: E501

        Request parameters for the primary type  # noqa: E501

        :return: The primary of this AggregateDataRequest.  # noqa: E501
        :rtype: AggregateRequest
        """
        return self._primary

    @primary.setter
    def primary(self, primary):
        """Sets the primary of this AggregateDataRequest.

        Request parameters for the primary type  # noqa: E501

        :param primary: The primary of this AggregateDataRequest.  # noqa: E501
        :type: AggregateRequest
        """
        if primary is None:
            raise ValueError("Invalid value for `primary`, must not be `None`")  # noqa: E501

        self._primary = primary

    @property
    def related(self):
        """Gets the related of this AggregateDataRequest.  # noqa: E501

        Request parameters for the related type  # noqa: E501

        :return: The related of this AggregateDataRequest.  # noqa: E501
        :rtype: list[RelatedDataRequest]
        """
        return self._related

    @related.setter
    def related(self, related):
        """Sets the related of this AggregateDataRequest.

        Request parameters for the related type  # noqa: E501

        :param related: The related of this AggregateDataRequest.  # noqa: E501
        :type: list[RelatedDataRequest]
        """

        self._related = related

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AggregateDataRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
