# coding: utf-8

"""
    NSX API

    VMware NSX REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.aws_gateway_config import AwsGatewayConfig  # noqa: F401,E501
from swagger_client.models.aws_gateway_status import AwsGatewayStatus  # noqa: F401,E501


class AwsGatewayInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gateway_status': 'AwsGatewayStatus',
        'configuration': 'AwsGatewayConfig'
    }

    attribute_map = {
        'gateway_status': 'gateway_status',
        'configuration': 'configuration'
    }

    def __init__(self, gateway_status=None, configuration=None):  # noqa: E501
        """AwsGatewayInfo - a model defined in Swagger"""  # noqa: E501

        self._gateway_status = None
        self._configuration = None
        self.discriminator = None

        if gateway_status is not None:
            self.gateway_status = gateway_status
        if configuration is not None:
            self.configuration = configuration

    @property
    def gateway_status(self):
        """Gets the gateway_status of this AwsGatewayInfo.  # noqa: E501

        Array of gateway statuses  # noqa: E501

        :return: The gateway_status of this AwsGatewayInfo.  # noqa: E501
        :rtype: AwsGatewayStatus
        """
        return self._gateway_status

    @gateway_status.setter
    def gateway_status(self, gateway_status):
        """Sets the gateway_status of this AwsGatewayInfo.

        Array of gateway statuses  # noqa: E501

        :param gateway_status: The gateway_status of this AwsGatewayInfo.  # noqa: E501
        :type: AwsGatewayStatus
        """

        self._gateway_status = gateway_status

    @property
    def configuration(self):
        """Gets the configuration of this AwsGatewayInfo.  # noqa: E501

        Configuration of this gateway  # noqa: E501

        :return: The configuration of this AwsGatewayInfo.  # noqa: E501
        :rtype: AwsGatewayConfig
        """
        return self._configuration

    @configuration.setter
    def configuration(self, configuration):
        """Sets the configuration of this AwsGatewayInfo.

        Configuration of this gateway  # noqa: E501

        :param configuration: The configuration of this AwsGatewayInfo.  # noqa: E501
        :type: AwsGatewayConfig
        """

        self._configuration = configuration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AwsGatewayInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
