# coding: utf-8

"""
    NSX API

    VMware NSX REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.resource import Resource  # noqa: F401,E501
from swagger_client.models.resource_link import ResourceLink  # noqa: F401,E501
from swagger_client.models.self_resource_link import SelfResourceLink  # noqa: F401,E501


class FirewallStats(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_self': 'SelfResourceLink',
        'links': 'list[ResourceLink]',
        'schema': 'str',
        'packet_count': 'str',
        'byte_count': 'str',
        'rule_id': 'str',
        'total_session_count': 'str',
        'session_count': 'str'
    }

    attribute_map = {
        '_self': '_self',
        'links': '_links',
        'schema': '_schema',
        'packet_count': 'packet_count',
        'byte_count': 'byte_count',
        'rule_id': 'rule_id',
        'total_session_count': 'total_session_count',
        'session_count': 'session_count'
    }

    def __init__(self, _self=None, links=None, schema=None, packet_count=None, byte_count=None, rule_id=None, total_session_count=None, session_count=None):  # noqa: E501
        """FirewallStats - a model defined in Swagger"""  # noqa: E501

        self.__self = None
        self._links = None
        self._schema = None
        self._packet_count = None
        self._byte_count = None
        self._rule_id = None
        self._total_session_count = None
        self._session_count = None
        self.discriminator = None

        if _self is not None:
            self._self = _self
        if links is not None:
            self.links = links
        if schema is not None:
            self.schema = schema
        if packet_count is not None:
            self.packet_count = packet_count
        if byte_count is not None:
            self.byte_count = byte_count
        if rule_id is not None:
            self.rule_id = rule_id
        if total_session_count is not None:
            self.total_session_count = total_session_count
        if session_count is not None:
            self.session_count = session_count

    @property
    def _self(self):
        """Gets the _self of this FirewallStats.  # noqa: E501


        :return: The _self of this FirewallStats.  # noqa: E501
        :rtype: SelfResourceLink
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this FirewallStats.


        :param _self: The _self of this FirewallStats.  # noqa: E501
        :type: SelfResourceLink
        """

        self.__self = _self

    @property
    def links(self):
        """Gets the links of this FirewallStats.  # noqa: E501

        The server will populate this field when returing the resource. Ignored on PUT and POST.  # noqa: E501

        :return: The links of this FirewallStats.  # noqa: E501
        :rtype: list[ResourceLink]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this FirewallStats.

        The server will populate this field when returing the resource. Ignored on PUT and POST.  # noqa: E501

        :param links: The links of this FirewallStats.  # noqa: E501
        :type: list[ResourceLink]
        """

        self._links = links

    @property
    def schema(self):
        """Gets the schema of this FirewallStats.  # noqa: E501


        :return: The schema of this FirewallStats.  # noqa: E501
        :rtype: str
        """
        return self._schema

    @schema.setter
    def schema(self, schema):
        """Sets the schema of this FirewallStats.


        :param schema: The schema of this FirewallStats.  # noqa: E501
        :type: str
        """

        self._schema = schema

    @property
    def packet_count(self):
        """Gets the packet_count of this FirewallStats.  # noqa: E501

        Aggregated number of packets processed by the rule.  # noqa: E501

        :return: The packet_count of this FirewallStats.  # noqa: E501
        :rtype: str
        """
        return self._packet_count

    @packet_count.setter
    def packet_count(self, packet_count):
        """Sets the packet_count of this FirewallStats.

        Aggregated number of packets processed by the rule.  # noqa: E501

        :param packet_count: The packet_count of this FirewallStats.  # noqa: E501
        :type: str
        """

        self._packet_count = packet_count

    @property
    def byte_count(self):
        """Gets the byte_count of this FirewallStats.  # noqa: E501

        Aggregated number of bytes processed by the rule.  # noqa: E501

        :return: The byte_count of this FirewallStats.  # noqa: E501
        :rtype: str
        """
        return self._byte_count

    @byte_count.setter
    def byte_count(self, byte_count):
        """Sets the byte_count of this FirewallStats.

        Aggregated number of bytes processed by the rule.  # noqa: E501

        :param byte_count: The byte_count of this FirewallStats.  # noqa: E501
        :type: str
        """

        self._byte_count = byte_count

    @property
    def rule_id(self):
        """Gets the rule_id of this FirewallStats.  # noqa: E501

        Rule Identifier of the Firewall rule. This is a globally unique number.  # noqa: E501

        :return: The rule_id of this FirewallStats.  # noqa: E501
        :rtype: str
        """
        return self._rule_id

    @rule_id.setter
    def rule_id(self, rule_id):
        """Sets the rule_id of this FirewallStats.

        Rule Identifier of the Firewall rule. This is a globally unique number.  # noqa: E501

        :param rule_id: The rule_id of this FirewallStats.  # noqa: E501
        :type: str
        """

        self._rule_id = rule_id

    @property
    def total_session_count(self):
        """Gets the total_session_count of this FirewallStats.  # noqa: E501

        Aggregated number of sessions processed by the all firewall rules  # noqa: E501

        :return: The total_session_count of this FirewallStats.  # noqa: E501
        :rtype: str
        """
        return self._total_session_count

    @total_session_count.setter
    def total_session_count(self, total_session_count):
        """Sets the total_session_count of this FirewallStats.

        Aggregated number of sessions processed by the all firewall rules  # noqa: E501

        :param total_session_count: The total_session_count of this FirewallStats.  # noqa: E501
        :type: str
        """

        self._total_session_count = total_session_count

    @property
    def session_count(self):
        """Gets the session_count of this FirewallStats.  # noqa: E501

        Aggregated number of sessions processed by the rule  # noqa: E501

        :return: The session_count of this FirewallStats.  # noqa: E501
        :rtype: str
        """
        return self._session_count

    @session_count.setter
    def session_count(self, session_count):
        """Sets the session_count of this FirewallStats.

        Aggregated number of sessions processed by the rule  # noqa: E501

        :param session_count: The session_count of this FirewallStats.  # noqa: E501
        :type: str
        """

        self._session_count = session_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FirewallStats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
