# coding: utf-8

"""
    NSX API

    VMware NSX REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.datasource import Datasource  # noqa: F401,E501
from swagger_client.models.footer import Footer  # noqa: F401,E501
from swagger_client.models.property_item import PropertyItem  # noqa: F401,E501
from swagger_client.models.resource_link import ResourceLink  # noqa: F401,E501
from swagger_client.models.self_resource_link import SelfResourceLink  # noqa: F401,E501
from swagger_client.models.tag import Tag  # noqa: F401,E501
from swagger_client.models.widget_configuration import WidgetConfiguration  # noqa: F401,E501


class LabelValueConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'navigation': 'str',
        'properties': 'list[PropertyItem]'
    }

    attribute_map = {
        'navigation': 'navigation',
        'properties': 'properties'
    }

    def __init__(self, navigation=None, properties=None):  # noqa: E501
        """LabelValueConfiguration - a model defined in Swagger"""  # noqa: E501

        self._navigation = None
        self._properties = None
        self.discriminator = None

        if navigation is not None:
            self.navigation = navigation
        self.properties = properties

    @property
    def navigation(self):
        """Gets the navigation of this LabelValueConfiguration.  # noqa: E501

        Hyperlink of the specified UI page that provides details.  # noqa: E501

        :return: The navigation of this LabelValueConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._navigation

    @navigation.setter
    def navigation(self, navigation):
        """Sets the navigation of this LabelValueConfiguration.

        Hyperlink of the specified UI page that provides details.  # noqa: E501

        :param navigation: The navigation of this LabelValueConfiguration.  # noqa: E501
        :type: str
        """

        self._navigation = navigation

    @property
    def properties(self):
        """Gets the properties of this LabelValueConfiguration.  # noqa: E501

        An array of label-value properties.  # noqa: E501

        :return: The properties of this LabelValueConfiguration.  # noqa: E501
        :rtype: list[PropertyItem]
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this LabelValueConfiguration.

        An array of label-value properties.  # noqa: E501

        :param properties: The properties of this LabelValueConfiguration.  # noqa: E501
        :type: list[PropertyItem]
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")  # noqa: E501

        self._properties = properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LabelValueConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
