# coding: utf-8

"""
    NSX API

    VMware NSX REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.enforcement_point_connection_info import EnforcementPointConnectionInfo  # noqa: F401,E501


class NSXTConnectionInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'password': 'str',
        'thumbprint': 'str'
    }

    attribute_map = {
        'username': 'username',
        'password': 'password',
        'thumbprint': 'thumbprint'
    }

    def __init__(self, username=None, password=None, thumbprint=None):  # noqa: E501
        """NSXTConnectionInfo - a model defined in Swagger"""  # noqa: E501

        self._username = None
        self._password = None
        self._thumbprint = None
        self.discriminator = None

        self.username = username
        self.password = password
        self.thumbprint = thumbprint

    @property
    def username(self):
        """Gets the username of this NSXTConnectionInfo.  # noqa: E501

        UserName  # noqa: E501

        :return: The username of this NSXTConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this NSXTConnectionInfo.

        UserName  # noqa: E501

        :param username: The username of this NSXTConnectionInfo.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this NSXTConnectionInfo.  # noqa: E501

        Password  # noqa: E501

        :return: The password of this NSXTConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this NSXTConnectionInfo.

        Password  # noqa: E501

        :param password: The password of this NSXTConnectionInfo.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def thumbprint(self):
        """Gets the thumbprint of this NSXTConnectionInfo.  # noqa: E501

        Thumbprint of EnforcementPoint. sha-256 hash represented in lower case hex.   # noqa: E501

        :return: The thumbprint of this NSXTConnectionInfo.  # noqa: E501
        :rtype: str
        """
        return self._thumbprint

    @thumbprint.setter
    def thumbprint(self, thumbprint):
        """Sets the thumbprint of this NSXTConnectionInfo.

        Thumbprint of EnforcementPoint. sha-256 hash represented in lower case hex.   # noqa: E501

        :param thumbprint: The thumbprint of this NSXTConnectionInfo.  # noqa: E501
        :type: str
        """
        if thumbprint is None:
            raise ValueError("Invalid value for `thumbprint`, must not be `None`")  # noqa: E501

        self._thumbprint = thumbprint

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NSXTConnectionInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
