# coding: utf-8

"""
    NSX API

    VMware NSX REST API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.managed_resource import ManagedResource  # noqa: F401,E501
from swagger_client.models.resource_link import ResourceLink  # noqa: F401,E501
from swagger_client.models.self_resource_link import SelfResourceLink  # noqa: F401,E501
from swagger_client.models.tag import Tag  # noqa: F401,E501
from swagger_client.models.transport_zone_profile_type_id_entry import TransportZoneProfileTypeIdEntry  # noqa: F401,E501


class TransportZone(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_self': 'SelfResourceLink',
        'links': 'list[ResourceLink]',
        'schema': 'str',
        'revision': 'int',
        'system_owned': 'bool',
        'display_name': 'str',
        'description': 'str',
        'tags': 'list[Tag]',
        'create_user': 'str',
        'protection': 'str',
        'create_time': 'int',
        'last_modified_time': 'int',
        'last_modified_user': 'str',
        'id': 'str',
        'resource_type': 'str',
        'host_switch_name': 'str',
        'host_switch_mode': 'str',
        'transport_type': 'str',
        'nested_nsx': 'bool',
        'transport_zone_profile_ids': 'list[TransportZoneProfileTypeIdEntry]'
    }

    attribute_map = {
        '_self': '_self',
        'links': '_links',
        'schema': '_schema',
        'revision': '_revision',
        'system_owned': '_system_owned',
        'display_name': 'display_name',
        'description': 'description',
        'tags': 'tags',
        'create_user': '_create_user',
        'protection': '_protection',
        'create_time': '_create_time',
        'last_modified_time': '_last_modified_time',
        'last_modified_user': '_last_modified_user',
        'id': 'id',
        'resource_type': 'resource_type',
        'host_switch_name': 'host_switch_name',
        'host_switch_mode': 'host_switch_mode',
        'transport_type': 'transport_type',
        'nested_nsx': 'nested_nsx',
        'transport_zone_profile_ids': 'transport_zone_profile_ids'
    }

    def __init__(self, _self=None, links=None, schema=None, revision=None, system_owned=None, display_name=None, description=None, tags=None, create_user=None, protection=None, create_time=None, last_modified_time=None, last_modified_user=None, id=None, resource_type=None, host_switch_name='nsxDefaultHostSwitch', host_switch_mode='STANDARD', transport_type=None, nested_nsx=False, transport_zone_profile_ids=None):  # noqa: E501
        """TransportZone - a model defined in Swagger"""  # noqa: E501

        self.__self = None
        self._links = None
        self._schema = None
        self._revision = None
        self._system_owned = None
        self._display_name = None
        self._description = None
        self._tags = None
        self._create_user = None
        self._protection = None
        self._create_time = None
        self._last_modified_time = None
        self._last_modified_user = None
        self._id = None
        self._resource_type = None
        self._host_switch_name = None
        self._host_switch_mode = None
        self._transport_type = None
        self._nested_nsx = None
        self._transport_zone_profile_ids = None
        self.discriminator = None

        if _self is not None:
            self._self = _self
        if links is not None:
            self.links = links
        if schema is not None:
            self.schema = schema
        if revision is not None:
            self.revision = revision
        if system_owned is not None:
            self.system_owned = system_owned
        if display_name is not None:
            self.display_name = display_name
        if description is not None:
            self.description = description
        if tags is not None:
            self.tags = tags
        if create_user is not None:
            self.create_user = create_user
        if protection is not None:
            self.protection = protection
        if create_time is not None:
            self.create_time = create_time
        if last_modified_time is not None:
            self.last_modified_time = last_modified_time
        if last_modified_user is not None:
            self.last_modified_user = last_modified_user
        if id is not None:
            self.id = id
        if resource_type is not None:
            self.resource_type = resource_type
        if host_switch_name is not None:
            self.host_switch_name = host_switch_name
        if host_switch_mode is not None:
            self.host_switch_mode = host_switch_mode
        self.transport_type = transport_type
        if nested_nsx is not None:
            self.nested_nsx = nested_nsx
        if transport_zone_profile_ids is not None:
            self.transport_zone_profile_ids = transport_zone_profile_ids

    @property
    def _self(self):
        """Gets the _self of this TransportZone.  # noqa: E501


        :return: The _self of this TransportZone.  # noqa: E501
        :rtype: SelfResourceLink
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this TransportZone.


        :param _self: The _self of this TransportZone.  # noqa: E501
        :type: SelfResourceLink
        """

        self.__self = _self

    @property
    def links(self):
        """Gets the links of this TransportZone.  # noqa: E501

        The server will populate this field when returing the resource. Ignored on PUT and POST.  # noqa: E501

        :return: The links of this TransportZone.  # noqa: E501
        :rtype: list[ResourceLink]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this TransportZone.

        The server will populate this field when returing the resource. Ignored on PUT and POST.  # noqa: E501

        :param links: The links of this TransportZone.  # noqa: E501
        :type: list[ResourceLink]
        """

        self._links = links

    @property
    def schema(self):
        """Gets the schema of this TransportZone.  # noqa: E501


        :return: The schema of this TransportZone.  # noqa: E501
        :rtype: str
        """
        return self._schema

    @schema.setter
    def schema(self, schema):
        """Sets the schema of this TransportZone.


        :param schema: The schema of this TransportZone.  # noqa: E501
        :type: str
        """

        self._schema = schema

    @property
    def revision(self):
        """Gets the revision of this TransportZone.  # noqa: E501

        The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected.  # noqa: E501

        :return: The revision of this TransportZone.  # noqa: E501
        :rtype: int
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """Sets the revision of this TransportZone.

        The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected.  # noqa: E501

        :param revision: The revision of this TransportZone.  # noqa: E501
        :type: int
        """

        self._revision = revision

    @property
    def system_owned(self):
        """Gets the system_owned of this TransportZone.  # noqa: E501

        Indicates system owned resource  # noqa: E501

        :return: The system_owned of this TransportZone.  # noqa: E501
        :rtype: bool
        """
        return self._system_owned

    @system_owned.setter
    def system_owned(self, system_owned):
        """Sets the system_owned of this TransportZone.

        Indicates system owned resource  # noqa: E501

        :param system_owned: The system_owned of this TransportZone.  # noqa: E501
        :type: bool
        """

        self._system_owned = system_owned

    @property
    def display_name(self):
        """Gets the display_name of this TransportZone.  # noqa: E501

        Defaults to ID if not set  # noqa: E501

        :return: The display_name of this TransportZone.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this TransportZone.

        Defaults to ID if not set  # noqa: E501

        :param display_name: The display_name of this TransportZone.  # noqa: E501
        :type: str
        """
        if display_name is not None and len(display_name) > 255:
            raise ValueError("Invalid value for `display_name`, length must be less than or equal to `255`")  # noqa: E501

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this TransportZone.  # noqa: E501

        Description of this resource  # noqa: E501

        :return: The description of this TransportZone.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TransportZone.

        Description of this resource  # noqa: E501

        :param description: The description of this TransportZone.  # noqa: E501
        :type: str
        """
        if description is not None and len(description) > 1024:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `1024`")  # noqa: E501

        self._description = description

    @property
    def tags(self):
        """Gets the tags of this TransportZone.  # noqa: E501

        Opaque identifiers meaningful to the API user  # noqa: E501

        :return: The tags of this TransportZone.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this TransportZone.

        Opaque identifiers meaningful to the API user  # noqa: E501

        :param tags: The tags of this TransportZone.  # noqa: E501
        :type: list[Tag]
        """

        self._tags = tags

    @property
    def create_user(self):
        """Gets the create_user of this TransportZone.  # noqa: E501

        ID of the user who created this resource  # noqa: E501

        :return: The create_user of this TransportZone.  # noqa: E501
        :rtype: str
        """
        return self._create_user

    @create_user.setter
    def create_user(self, create_user):
        """Sets the create_user of this TransportZone.

        ID of the user who created this resource  # noqa: E501

        :param create_user: The create_user of this TransportZone.  # noqa: E501
        :type: str
        """

        self._create_user = create_user

    @property
    def protection(self):
        """Gets the protection of this TransportZone.  # noqa: E501

        Protection status is one of the following: PROTECTED - the client who retrieved the entity is not allowed             to modify it. NOT_PROTECTED - the client who retrieved the entity is allowed                 to modify it REQUIRE_OVERRIDE - the client who retrieved the entity is a super                    user and can modify it, but only when providing                    the request header X-Allow-Overwrite=true. UNKNOWN - the _protection field could not be determined for this           entity.   # noqa: E501

        :return: The protection of this TransportZone.  # noqa: E501
        :rtype: str
        """
        return self._protection

    @protection.setter
    def protection(self, protection):
        """Sets the protection of this TransportZone.

        Protection status is one of the following: PROTECTED - the client who retrieved the entity is not allowed             to modify it. NOT_PROTECTED - the client who retrieved the entity is allowed                 to modify it REQUIRE_OVERRIDE - the client who retrieved the entity is a super                    user and can modify it, but only when providing                    the request header X-Allow-Overwrite=true. UNKNOWN - the _protection field could not be determined for this           entity.   # noqa: E501

        :param protection: The protection of this TransportZone.  # noqa: E501
        :type: str
        """

        self._protection = protection

    @property
    def create_time(self):
        """Gets the create_time of this TransportZone.  # noqa: E501

        Timestamp of resource creation  # noqa: E501

        :return: The create_time of this TransportZone.  # noqa: E501
        :rtype: int
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this TransportZone.

        Timestamp of resource creation  # noqa: E501

        :param create_time: The create_time of this TransportZone.  # noqa: E501
        :type: int
        """

        self._create_time = create_time

    @property
    def last_modified_time(self):
        """Gets the last_modified_time of this TransportZone.  # noqa: E501

        Timestamp of last modification  # noqa: E501

        :return: The last_modified_time of this TransportZone.  # noqa: E501
        :rtype: int
        """
        return self._last_modified_time

    @last_modified_time.setter
    def last_modified_time(self, last_modified_time):
        """Sets the last_modified_time of this TransportZone.

        Timestamp of last modification  # noqa: E501

        :param last_modified_time: The last_modified_time of this TransportZone.  # noqa: E501
        :type: int
        """

        self._last_modified_time = last_modified_time

    @property
    def last_modified_user(self):
        """Gets the last_modified_user of this TransportZone.  # noqa: E501

        ID of the user who last modified this resource  # noqa: E501

        :return: The last_modified_user of this TransportZone.  # noqa: E501
        :rtype: str
        """
        return self._last_modified_user

    @last_modified_user.setter
    def last_modified_user(self, last_modified_user):
        """Sets the last_modified_user of this TransportZone.

        ID of the user who last modified this resource  # noqa: E501

        :param last_modified_user: The last_modified_user of this TransportZone.  # noqa: E501
        :type: str
        """

        self._last_modified_user = last_modified_user

    @property
    def id(self):
        """Gets the id of this TransportZone.  # noqa: E501

        Unique identifier of this resource  # noqa: E501

        :return: The id of this TransportZone.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TransportZone.

        Unique identifier of this resource  # noqa: E501

        :param id: The id of this TransportZone.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def resource_type(self):
        """Gets the resource_type of this TransportZone.  # noqa: E501

        The type of this resource.  # noqa: E501

        :return: The resource_type of this TransportZone.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this TransportZone.

        The type of this resource.  # noqa: E501

        :param resource_type: The resource_type of this TransportZone.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def host_switch_name(self):
        """Gets the host_switch_name of this TransportZone.  # noqa: E501

        If this name is unset or empty then the default host switch name will be used.  # noqa: E501

        :return: The host_switch_name of this TransportZone.  # noqa: E501
        :rtype: str
        """
        return self._host_switch_name

    @host_switch_name.setter
    def host_switch_name(self, host_switch_name):
        """Sets the host_switch_name of this TransportZone.

        If this name is unset or empty then the default host switch name will be used.  # noqa: E501

        :param host_switch_name: The host_switch_name of this TransportZone.  # noqa: E501
        :type: str
        """

        self._host_switch_name = host_switch_name

    @property
    def host_switch_mode(self):
        """Gets the host_switch_mode of this TransportZone.  # noqa: E501

        STANDARD mode applies to all the hypervisors. ENS mode stands for Enhanced Networking Stack. This feature is only available for ESX hypervisor. It is not available on KVM, EDGE and Public Cloud Gateway etc. When a Transport Zone mode is set to ENS, only Transport Nodes of type ESX can participate in such a Transport Zone.  # noqa: E501

        :return: The host_switch_mode of this TransportZone.  # noqa: E501
        :rtype: str
        """
        return self._host_switch_mode

    @host_switch_mode.setter
    def host_switch_mode(self, host_switch_mode):
        """Sets the host_switch_mode of this TransportZone.

        STANDARD mode applies to all the hypervisors. ENS mode stands for Enhanced Networking Stack. This feature is only available for ESX hypervisor. It is not available on KVM, EDGE and Public Cloud Gateway etc. When a Transport Zone mode is set to ENS, only Transport Nodes of type ESX can participate in such a Transport Zone.  # noqa: E501

        :param host_switch_mode: The host_switch_mode of this TransportZone.  # noqa: E501
        :type: str
        """
        allowed_values = ["STANDARD", "ENS"]  # noqa: E501
        if host_switch_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `host_switch_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(host_switch_mode, allowed_values)
            )

        self._host_switch_mode = host_switch_mode

    @property
    def transport_type(self):
        """Gets the transport_type of this TransportZone.  # noqa: E501

        The transport type of this transport zone.  # noqa: E501

        :return: The transport_type of this TransportZone.  # noqa: E501
        :rtype: str
        """
        return self._transport_type

    @transport_type.setter
    def transport_type(self, transport_type):
        """Sets the transport_type of this TransportZone.

        The transport type of this transport zone.  # noqa: E501

        :param transport_type: The transport_type of this TransportZone.  # noqa: E501
        :type: str
        """
        if transport_type is None:
            raise ValueError("Invalid value for `transport_type`, must not be `None`")  # noqa: E501
        allowed_values = ["OVERLAY", "VLAN"]  # noqa: E501
        if transport_type not in allowed_values:
            raise ValueError(
                "Invalid value for `transport_type` ({0}), must be one of {1}"  # noqa: E501
                .format(transport_type, allowed_values)
            )

        self._transport_type = transport_type

    @property
    def nested_nsx(self):
        """Gets the nested_nsx of this TransportZone.  # noqa: E501

        The flag only need to be set in nested NSX environment.  # noqa: E501

        :return: The nested_nsx of this TransportZone.  # noqa: E501
        :rtype: bool
        """
        return self._nested_nsx

    @nested_nsx.setter
    def nested_nsx(self, nested_nsx):
        """Sets the nested_nsx of this TransportZone.

        The flag only need to be set in nested NSX environment.  # noqa: E501

        :param nested_nsx: The nested_nsx of this TransportZone.  # noqa: E501
        :type: bool
        """

        self._nested_nsx = nested_nsx

    @property
    def transport_zone_profile_ids(self):
        """Gets the transport_zone_profile_ids of this TransportZone.  # noqa: E501

        Identifiers of the transport zone profiles associated with this TransportZone.  # noqa: E501

        :return: The transport_zone_profile_ids of this TransportZone.  # noqa: E501
        :rtype: list[TransportZoneProfileTypeIdEntry]
        """
        return self._transport_zone_profile_ids

    @transport_zone_profile_ids.setter
    def transport_zone_profile_ids(self, transport_zone_profile_ids):
        """Sets the transport_zone_profile_ids of this TransportZone.

        Identifiers of the transport zone profiles associated with this TransportZone.  # noqa: E501

        :param transport_zone_profile_ids: The transport_zone_profile_ids of this TransportZone.  # noqa: E501
        :type: list[TransportZoneProfileTypeIdEntry]
        """

        self._transport_zone_profile_ids = transport_zone_profile_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransportZone):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
